![alt text](http://infra.heurys.com.br/summerschool/fundamentos.000.png)

## Importando a biblioteca do Numpy

In [1]:
import numpy as np

# 1 - Criando arrays com Numpy

![alt text](http://infra.heurys.com.br/summerschool/numpy.create.PNG)

> ## 1.1- Array de várias dimensões (array)
> #### ***Objetivo***: Criar um array de uma ou várias dimensões.
> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.array.html

In [4]:
vetor  = np.array([1,2,3])
print('Vetor:\n',vetor)

Vetor:
 [1 2 3]


In [5]:
matriz = np.array([[1,2,3], [4,5,6]])
print('Matriz:\n',matriz)

Matriz:
 [[1 2 3]
 [4 5 6]]


In [7]:
matriz_2_2 = np.matrix('1 2; 3 4')
print('Matriz 2x2:\n',matriz_2_2)

Matriz 2x2:
 [[1 2]
 [3 4]]


In [8]:
matriz_2_3 = np.matrix([[1,2,3],[4,5,6]])
print('Matriz 2x3:\n',matriz_2_3)

Matriz 2x3:
 [[1 2 3]
 [4 5 6]]


In [9]:
matriz_3_2_3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print('Matriz 2x3x3:\n',matriz_3_2_3)

Matriz 2x3x3:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


> ## 1.2- Arrays com dados sequenciais (arange)
> #### ***Objetivo***: Retornar um array com valores dentro de um intervalo. É importante lembrar que o parâmetro final (stop) do intervalo não será retornado.
> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.arange.html

In [11]:
vetor_16 = np.arange(1,17)
print('Vetor 1x16:\n',vetor_16, '\n')

vetor_10_a_25 = np.arange(10,25,5)
print('Vetor 10-25:\n', vetor_10_a_25, '\n')

Vetor 1x16:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16] 

Vetor 10-25:
 [10 15 20] 



> ## 1.3- Arrays não inicializados > valores aleatórios (empty)
> #### ***Objetivo***: Retornar um array não incializado
> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.empty.html
> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.empty_like.html

In [14]:
matriz_2_2_empty = np.empty((2,2))
print('Matriz 2x2 (empty):\n',matriz_2_2_empty, '\n')

matriz_empty_like = np.empty_like(matriz_2_2_empty)
print('Matriz (empty_like):\n',matriz_empty_like)

Matriz 2x2 (empty):
 [[ 0.  0.]
 [ 0.  0.]] 

Matriz (empty_like):
 [[ 0.  0.]
 [ 0.  0.]]


> ## 1.4- Arrays inicializados com valores randômicos (random)
> #### ***Objetivo***: Retornar um array incializado com valores randômicos no intervalo de 0 - 1.
> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.random.random.html

In [15]:
matriz_2_2_random = np.random.random((2,2))
print('Matriz 2x2 (random):\n',matriz_2_2_random)

Matriz 2x2 (random):
 [[ 0.1228233   0.43939755]
 [ 0.41558203  0.4709355 ]]


> ## 1.5- Arrays inicializados com 1 (ones)
> #### ***Objetivo***: Retornar uma matriz incializada com zero
> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ones.html
> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ones_like.html

In [16]:
matriz_3_3_3_ones = np.ones((3,3,3))
print('Matriz 3x3x3 (ones):\n', matriz_3_3_3_ones, '\n')

matriz_ones_like = np.ones_like(matriz_2_2_empty)
print('Matriz (ones like):\n', matriz_ones_like)

Matriz 3x3x3 (ones):
 [[[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]] 

Matriz (ones like):
 [[ 1.  1.]
 [ 1.  1.]]


> ## 1.6- Arrays inicializados com um número (full)
> #### ***Objetivo***: Retornar um array incializado com um valor definido.
> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.full.html
> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.full_like.html

In [17]:
matriz_4_4_full = np.full((4,4), 10)
print('Matriz 4x4 (full):\n',matriz_4_4_full, '\n')


matriz_full_like = np.full_like(matriz_2_2_empty, 5)
print('Matriz (full like):\n', matriz_full_like)

Matriz 4x4 (full):
 [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]] 

Matriz (full like):
 [[ 5.  5.]
 [ 5.  5.]]


> ## 1.7- Arrays inicializados com 0 (zeros)
> #### ***Objetivo***: Retornar um array incializado com zeros.
> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.zeros.html
> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.zeros_like.html

In [18]:
matriz_3_3 = np.zeros((3,3))
print('Matriz 3x3:\n',matriz_3_3, '\n')


matriz_zeros_like = np.zeros_like(matriz_2_2_empty)
print('Matriz (zeros like):\n', matriz_zeros_like)

Matriz 3x3:
 [[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]] 

Matriz (zeros like):
 [[ 0.  0.]
 [ 0.  0.]]


> ## 1.8- Arrays inicializados com valores entre dois números (linspace)
> #### ***Objetivo***: Retornar um array incializado com um valor definido em um range. É importante lembrar que o parâmetro final (stop) do intervalo não será retornado.
> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linspace.html

In [19]:
vetor_0_a_2 = np.linspace(0,1,9)
print('vetor 0-2:\n', vetor_0_a_2)

vetor 0-2:
 [ 0.     0.125  0.25   0.375  0.5    0.625  0.75   0.875  1.   ]


> ## 1.9 - Arrays bidimensionais diagonais (diag)
> #### ***Objetivo***: Criar uma matriz quadrada a partir de uma diagonal ou extrair a diagonal de uma matriz.
> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.diag.html

In [20]:
matriz_diagonal = np.diag([1,2,3])
print('Matriz diagonal:\n', matriz_diagonal)

Matriz diagonal:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [21]:
matriz_diagonal_1p = np.diag([1,2,3],1)
print('Matriz diagonal +1:\n', matriz_diagonal_1p)

Matriz diagonal +1:
 [[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]


In [22]:
matriz_diagonal_1n = np.diag([1,2,3], -1)
print('Matriz diagonal -1:\n', matriz_diagonal_1n)

Matriz diagonal -1:
 [[0 0 0 0]
 [1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [23]:
matriz_base_3_3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Matriz 3 x 3: \n', matriz_base_3_3, '\n')

diagonal = np.diag(matriz_base_3_3)
print('Diagonal: \n', diagonal, '\n')

matriz_diagonal_nova = np.diag(diagonal)
print('Matriz diagonal nova: \n', matriz_diagonal_nova)

Matriz 3 x 3: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

Diagonal: 
 [1 5 9] 

Matriz diagonal nova: 
 [[1 0 0]
 [0 5 0]
 [0 0 9]]


> ## 1.10 - Arrays bidimensionais de identidade (eye, identity)
> #### ***Objetivo eye***: Criar um array inicializando a diagonal com 1 e o restante com zeros.
> #### ***Objetivo identity***: Criar uma matriz quadrada inicializando a diagonal com 1 e o restante com zeros.
> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.eye.html
> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.identity.html

In [24]:
matriz_identidade = np.eye(3, dtype=np.int16)
print('Matriz identidade:\n', matriz_identidade, '\n')

matriz_identidade = np.identity(3, dtype=np.int16)
print('Matriz identidade:\n', matriz_identidade)

Matriz identidade:
 [[1 0 0]
 [0 1 0]
 [0 0 1]] 

Matriz identidade:
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [25]:
matriz_1p = np.eye(3, k=1, dtype=np.int16)
print('Matriz +1:\n', matriz_1p, '\n')

matriz_1n = np.eye(3, k=-1, dtype=np.int16)
print('Matriz -1:\n', matriz_1n, '\n')

matriz_2col = np.eye(3, 2, k=0, dtype=np.int16)
print('Matriz identidade 2 colunas:\n', matriz_2col)

Matriz +1:
 [[0 1 0]
 [0 0 1]
 [0 0 0]] 

Matriz -1:
 [[0 0 0]
 [1 0 0]
 [0 1 0]] 

Matriz identidade 2 colunas:
 [[1 0]
 [0 1]
 [0 0]]


> ## 1.11 - Recuperando informações dos arrays

>> ### 1.11.1 - Formato do array (shape)
>> #### ***Objetivo***: Retornar o formato de um array.
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.shape.html

In [26]:
print('formato: ', matriz_3_3.shape)
print('formato: ', matriz_2_2.shape)
print('formato: ', matriz_3_2_3.shape)
print('formato: ', vetor_0_a_2.shape)

formato:  (3, 3)
formato:  (2, 2)
formato:  (3, 2, 3)
formato:  (9,)


>> ### 1.11.2 - Tamanho do array (size)
>> #### ***Objetivo***: Retornar o número de elementos de um array.
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.size.html

In [27]:
print('tamanho: ', matriz_3_3.size)
print('tamanho: ', matriz_2_2.size)
print('tamanho: ', matriz_3_2_3.size)
print('tamanho: ', vetor_0_a_2.size)

tamanho:  9
tamanho:  4
tamanho:  18
tamanho:  9


>> ### 1.11.3 - Dimensão do array (ndim)
>> #### ***Objetivo***: Retornar a quantidade de dimensões de um array.
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.ndim.html

In [28]:
print('dimensão: ', matriz_3_3.ndim)
print('dimensão: ', matriz_3_2_3.ndim)
print('dimensão: ', vetor_0_a_2.ndim)

dimensão:  2
dimensão:  3
dimensão:  1


>> ### 1.11.4 - Tipo dos elementos do array (dtype)
>> #### ***Objetivo***: Retornar o tipo dos elementos de um array.
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.dtype.html

In [29]:
print('tipo: ', matriz_3_3.dtype)

tipo:  float64


>> ### 1.11.5 - Tamanho em bytes do array (itemsize)
>> #### ***Objetivo***: Retornar a quantidade de bytes utilizada pelo array.
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.itemsize.html

In [ ]:
print(matriz_3_3.itemsize, 'bytes')

# 2 - Transformando os arrays

![alt text](http://infra.heurys.com.br/summerschool/numpy.transform.01.png)

In [ ]:
vetor_base = np.arange(1,17)
print('1 x 16:\n', vetor_base)

> ## 2.1 - Transformando um vetor em uma matriz, com ordem dos elementos = "C" ou "F"ortran. (reshape)
>> #### ***Objetivo***: Retornar um novo formato de array sem alterar os dados e o formato original.
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.reshape.html

In [ ]:
matriz_4_4_c = vetor_base.reshape((4,4),order='C')
print('4 x 4 ordem C:\n', matriz_4_4_c, '\n')

In [ ]:
matriz_4_4_f = vetor_base.reshape((4,4),order='F')
print('4 x 4 ordem F:\n', matriz_4_4_f, '\n')

In [ ]:
matriz_2_8 = np.reshape(vetor_base, (2,8), order='C')
print('2 x 8:\n', matriz_2_8, '\n')

In [ ]:
matriz_8_2 = np.reshape(vetor_base, (8,2))
print('8 x 2:\n', matriz_8_2, '\n')

In [ ]:
matriz_2_dim_column = np.reshape(vetor_base, (2,-1))
print('2 x D:\n', matriz_2_dim_column)

In [ ]:
matriz_2_8_b = np.reshape(matriz_4_4_f,(2,8))
print('2 x 8 b:\n', matriz_2_8_b)

> ## 2.2 - Transformando um vetor em uma matriz, com ordem dos elementos = "C" ou "F"ortran. (resize)
>> #### ***Objetivo***: Transforma o array em um novo formato.
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.resize.html

In [ ]:
vetor_base.resize((2,8))
print('2 x 8:\n', vetor_base)

> ## 2.3 - Transformando uma matriz em um vetor, com ordem dos elementos = "C" ou "F"ortran. (ravel)
>> #### ***Objetivo***: Retornar um array de uma dimensão.
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ravel.html

In [ ]:
print('Matriz 4 x 4 ordem Fortran:\n', matriz_4_4_f, '\n')

vetor_16_b = np.ravel(matriz_4_4_f, order='F')
print('1 x 16:\n', vetor_16_b)

In [ ]:
matriz_2_8_c = np.reshape(np.ravel(matriz_4_4_f, order='F'),(2,8))
print('2 x 8 c:\n', matriz_2_8_c)

> ## 2.4 - Extraindo elementos de um array de duas dimensões (slice)
>> #### ***Objetivo***: Retornar parte de um array.
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html

In [ ]:
print('Matriz base: \n', matriz_4_4_c, '\n')

In [ ]:
# sintaxe: [idx_line, idx_column]
quinto_elemento = matriz_4_4_c[1,0]
print('linha 2 coluna 1 = ', quinto_elemento)

In [ ]:
# sintaxe: [idx_line, idx_column : qtd_line]
duas_linhas = matriz_4_4_c[:2]
print('duas linhas:\n', duas_linhas)

In [ ]:
# sintaxe: [idx_line, idx_column : qtd_line, idx_col]
ultima_coluna = matriz_4_4_c[:4,3]
print('ultima coluna:\n', ultima_coluna)

In [ ]:
# sintaxe: [idx_line, idx_column : array(idx_column)]
duas_colunas = matriz_4_4_c[0 : 4, [1, 2]]
print('duas colunas:\n', duas_colunas)

In [ ]:
# sintaxe: [idx_line, idx_column : array(idx_column)]
duas_colunas_b = matriz_4_4_c[:,[1, 2]]
print('duas colunas b:\n', duas_colunas_b)

In [ ]:
# sintaxe: [idx_line, idx_column : array(idx_column)]
matriz_2_2_part = matriz_4_4_c[1:3,[1, 2]]
print('2 x 2 part:\n', matriz_2_2_part)

In [ ]:
# sintaxe: [array(idx_line), array(idx_column)]
vetor = matriz_4_4_c[[1, 2, 3],[0, 2, 1]]
print('vetor part:\n', vetor)

> ## 2.4 - Extraindo elementos de um array de uma dimensão (slice)
>> #### ***Objetivo***: Retornar parte de um array.
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html

In [ ]:
vetor_base = np.arange(1,17)
print('1 x 16:\n', vetor_base)

In [ ]:
vetor_impar = vetor_base[0:16:2]
print('vetor impar:\n',vetor_impar)

In [ ]:
sem_os_tres_ultimos = vetor_base[:-3]
print('sem três os últimos:\n',sem_os_tres_ultimos)

In [ ]:
somente_os_tres_ultimos = vetor_base[-3:]
print('somente os três últimos:\n',somente_os_tres_ultimos)

In [ ]:
nova_dimensao = vetor_base[:,np.newaxis]
print('nova dimensão:\n', nova_dimensao)

> ## 2.5 - Concatenando arrays (concatenate, vstack, hstack)

![alt text](http://infra.heurys.com.br/summerschool/numpy.transform.02.png)

>> #### ***Objetivo***: Retornar um array concatenado.
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.concatenate.html
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.vstack.html
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.hstack.html

In [3]:
matriz_1 = np.array(((1, 2), (3, 4)))
matriz_2 = np.array(((5, 6), (7, 8)))
matriz_3 = np.array(((9, 10), (11, 12)))

print('Matriz 1:', matriz_1,'Matriz 2:', matriz_2,'Matriz 3:', matriz_3, sep='\n')

Matriz 1:
[[1 2]
 [3 4]]
Matriz 2:
[[5 6]
 [7 8]]
Matriz 3:
[[ 9 10]
 [11 12]]


In [4]:
matriz_concatenada = np.concatenate((matriz_1, matriz_2, matriz_3))
print('Matriz concatenada: \n', matriz_concatenada)

Matriz concatenada: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
matriz_a = np.array([ [1,2,3], [4,5,6], [7,8,9] ])
print('Matriz A:\n', matriz_a)

matriz_b = np.array([ [1,1,1], [2,2,2], [3,3,3] ])
print('Matriz B:\n',matriz_b)

In [ ]:
# Concatenando um array na vertical
print('Vertical:\n',np.vstack((matriz_a, matriz_b)))

# Concatenando um array na horizontal
print('Horizontal:\n',np.hstack((matriz_a, matriz_b)))

> ## 2.6 - Dividindo arrays (split, vsplit, hsplit)

![alt text](http://infra.heurys.com.br/summerschool/numpy.transform.03.png)

>> #### ***Objetivo***: Retornar vários arrays divididos.
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.split.html
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.vsplit.html
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.hsplit.html

In [ ]:
matriz_1 = np.array(((1, 2), (3, 4), (5, 6) , (7, 8), (9, 10), (11, 12)))
print('Matriz 1:\n', matriz_1)

In [ ]:
split = np.split(matriz_1, 3)
print('Split Parte 1:\n', split[0])
print('Split Parte 2:\n', split[1])
print('Split Parte 3:\n', split[2])

In [ ]:
split_vertical = np.vsplit(matriz_1, 2)
print ('Split Vertical Parte 1:\n', split_vertical[0])
print ('Split Vertical Parte 2:\n', split_vertical[1])

In [ ]:
split_horizontal = np.hsplit(matriz_1, 2)
print ('Split Horizontal Parte 1:\n', split_horizontal[0])
print ('Split Horizontal Parte 2:\n', split_horizontal[1])

# 3 - Cálculos com os arrays

![alt text](http://infra.heurys.com.br/summerschool/numpy.calc.01.png)

In [ ]:
matriz_base = np.array([ [1,2], [3,4]])
print('Matriz Base:\n', matriz_base)

> ## 3.1 - Transposta, Inversa, Determinante, Autovalores e AutoVetores
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.T.html
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.inv.html
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.det.html
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.eig.html

In [ ]:
# Matriz transposta
print('Matriz Trasposta:\n', matriz_base.T)

In [ ]:
# Inversa da Matriz
print('Inversa:\n', np.linalg.inv(matriz_base))

In [ ]:
# Determinante da Matriz
print('Determinante:\n', np.linalg.det(matriz_base))

In [ ]:
# Autovalores e autovetores
valores, vetores = np.linalg.eig(matriz_base)
print('Autovalores:\n', valores)
print('Autovetores:\n', vetores)

> ## 3.2 - Soma, soma da diagonal, soma de um eixo, máximo, mínimo
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.sum.html
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.trace.html
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.max.html
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndarray.min.html

In [ ]:
# Soma da Matriz
print('Soma:\n', np.sum(matriz_base))
print('Soma da Coluna:\n', np.sum(matriz_base, axis=0))
print('Soma da Linha:\n', np.sum(matriz_base, axis=1))

In [ ]:
# Somando a diagonal da Matriz
print('Soma Diagonal:\n', np.trace(matriz_base))

In [ ]:
# Maior elemento da matriz
print('Maior:\n', np.max(matriz_base))
print('Maior da Coluna:\n', np.max(matriz_base, axis=0))
print('Maior da Linha:\n', np.max(matriz_base, axis=1))

In [ ]:
# Menor elemento da matriz
print('Menor:\n', np.min(matriz_base))
print('Menor da Coluna:\n', np.min(matriz_base, axis=0))
print('Menor da Linha:\n', np.min(matriz_base, axis=1))

> ## 3.3 - Desvio Padrão, Raiz, Seno, Cosseno, Tangente, Exponencial e Logaritmo
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.std.html
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.sqrt.html
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.sin.html
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.cos.html
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.tan.html
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.exp.html
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.log.html

In [ ]:
# Desvio Padrão da Matriz
print('Desvio padrão:\n', np.std(matriz_base))
print('Desvio padrão da Coluna:\n', np.std(matriz_base, axis=0))
print('Desvio padrão da Linha:\n', np.std(matriz_base, axis=1))

In [ ]:
# Raiz da Matriz
print('Raiz:\n', np.sqrt(matriz_base))

In [ ]:
# Seno da Matriz
print('Seno:\n', np.sin(matriz_base))

In [ ]:
# Cosseno da Matriz
print('Cosseno:\n', np.cos(matriz_base))

In [ ]:
# Tangente da Matriz
print('Tangente:\n', np.tan(matriz_base))

In [ ]:
# Exponencial da Matriz
print('Exponencial:\n', np.exp(matriz_base))

In [ ]:
# Logaritmo da Matriz
print('Logaritmo:\n', np.log(matriz_base))
print('Logaritmo base 10:\n', np.log10(matriz_base))

> ## 3.4 - Matriz de covariância 
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.cov.html
>> ##### documentação: https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.dot.html

In [ ]:
# Matriz Covariância
print('Matriz Covariância:\n', np.cov(matriz_base))

In [ ]:
# Matriz A
matriz_a = np.array(((2, 3), (4, 5)))

# Matriz B
matriz_b = np.array(((6, 7), (8, 9)))
c = np.dot(matriz_a,matriz_b)
print(c)

> ## 3.5 - Operações com os arrays

In [14]:
# Matriz Base
matriz_a = np.array(((1,2,3), (4,5,6)))
matriz_b = np.array(((2,2,2), (4,4,4)))

print('Matriz A:', matriz_a, '\nMatriz B:', matriz_b, sep='\n')
                    
adicao = matriz_a + matriz_b
print('\nAdição: \n', adicao)                    

teste_bool = matriz_a > 2
print('\nMaior que dois: \n', teste_bool)

multiplicacao = matriz_b * 3
print('\nMultiplicação: \n', multiplicacao)

comparacao = matriz_a == matriz_b
print('\nComparando 2 Matriz:\n',comparacao)

Matriz A:
[[1 2 3]
 [4 5 6]]

Matriz B:
[[2 2 2]
 [4 4 4]]

Adição: 
 [[ 3  4  5]
 [ 8  9 10]]

Maior que dois: 
 [[False False  True]
 [ True  True  True]]

Multiplicação: 
 [[ 6  6  6]
 [12 12 12]]

Comparando 2 Matriz:
 [[False  True False]
 [ True False False]]
